const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAIL: 'GET_CURRENT_USER_FAIL',
    UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
    UPDATE_USER_PROFILE_FAIL: "UPDATE_USER_PROFILE_FAIL",
    GET_MY_ADDRESSES_REQUEST: 'GET_MY_ADDRESSES_REQUEST',
    GET_MY_ADDRESSES_SUCCESS: 'GET_MY_ADDRESSES_SUCCESS',
    GET_MY_ADDRESSES_FAIL: 'GET_MY_ADDRESSES_FAIL',
    GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_FAIL: 'GET_COUNTRIES_FAIL',
    GET_PROVINCES_SUCCESS: 'GET_PROVINCES_SUCCESS',
    GET_WARDS_SUCCESS: 'GET_WARDS_SUCCESS',
}

export default actionTypes