const actionTypes = {
    // Auth
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    CLEAR_AUTH_MSG: 'CLEAR_AUTH_MSG',
    LOGOUT: 'LOGOUT',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAIL: 'GET_CURRENT_USER_FAIL',
    
    // Users
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAIL: 'GET_USERS_FAIL',
    
    // Roles
    GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
    GET_ROLES_FAIL: 'GET_ROLES_FAIL',
    
    // Products
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL',
    GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
    GET_PRODUCT_DETAIL_FAIL: 'GET_PRODUCT_DETAIL_FAIL',
    GET_PRODUCT_REVIEWS_SUCCESS: 'GET_PRODUCT_REVIEWS_SUCCESS',
    GET_PRODUCT_REVIEWS_FAIL: 'GET_PRODUCT_REVIEWS_FAIL',
    
    // Brands
    GET_BRANDS_SUCCESS: 'GET_BRANDS_SUCCESS',
    GET_BRANDS_FAIL: 'GET_BRANDS_FAIL',
    GET_BRAND_DETAIL_SUCCESS: 'GET_BRAND_DETAIL_SUCCESS',
    GET_BRAND_DETAIL_FAIL: 'GET_BRAND_DETAIL_FAIL',
    
    // Categories
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAIL: 'GET_CATEGORIES_FAIL',
    GET_CATEGORY_DETAIL_SUCCESS: 'GET_CATEGORY_DETAIL_SUCCESS',
    GET_CATEGORY_DETAIL_FAIL: 'GET_CATEGORY_DETAIL_FAIL',
    
    // Cart
    GET_MY_CART_SUCCESS: 'GET_MY_CART_SUCCESS',
    GET_MY_CART_FAIL: 'GET_MY_CART_FAIL',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAIL: 'ADD_TO_CART_FAIL',
    
    // Orders
    GET_MY_ORDERS_SUCCESS: 'GET_MY_ORDERS_SUCCESS',
    GET_MY_ORDERS_FAIL: 'GET_MY_ORDERS_FAIL',
    GET_ALL_ORDERS_ADMIN_REQUEST: 'GET_ALL_ORDERS_ADMIN_REQUEST',
    GET_ALL_ORDERS_ADMIN_SUCCESS: 'GET_ALL_ORDERS_ADMIN_SUCCESS',
    GET_ALL_ORDERS_ADMIN_FAIL: 'GET_ALL_ORDERS_ADMIN_FAIL',
    GET_ORDER_DETAIL_ADMIN_SUCCESS: 'GET_ORDER_DETAIL_ADMIN_SUCCESS',
    GET_ORDER_DETAIL_ADMIN_FAIL: 'GET_ORDER_DETAIL_ADMIN_FAIL',
    CONFIRM_ORDER_ADMIN_SUCCESS: 'CONFIRM_ORDER_ADMIN_SUCCESS',
    CONFIRM_ORDER_ADMIN_FAIL: 'CONFIRM_ORDER_ADMIN_FAIL',
    
    // Coupons
    GET_MY_COUPONS_SUCCESS: 'GET_MY_COUPONS_SUCCESS',
    GET_MY_COUPONS_FAIL: 'GET_MY_COUPONS_FAIL',
    GET_ALL_COUPONS_ADMIN_SUCCESS: 'GET_ALL_COUPONS_ADMIN_SUCCESS',
    
    // Addresses
    GET_MY_ADDRESSES_REQUEST: 'GET_MY_ADDRESSES_REQUEST',
    GET_MY_ADDRESSES_SUCCESS: 'GET_MY_ADDRESSES_SUCCESS',
    GET_MY_ADDRESSES_FAIL: 'GET_MY_ADDRESSES_FAIL',
    
    // Locations
    GET_PROVINCES_SUCCESS: 'GET_PROVINCES_SUCCESS',
    GET_WARDS_SUCCESS: 'GET_WARDS_SUCCESS',
    
    // Reviews (Admin)
    GET_ALL_REVIEWS_ADMIN_SUCCESS: 'GET_ALL_REVIEWS_ADMIN_SUCCESS',
    GET_ALL_REVIEWS_ADMIN_FAIL: 'GET_ALL_REVIEWS_ADMIN_FAIL',
    GET_REVIEW_DETAIL_ADMIN_SUCCESS: 'GET_REVIEW_DETAIL_ADMIN_SUCCESS',
    GET_REVIEW_DETAIL_ADMIN_FAIL: 'GET_REVIEW_DETAIL_ADMIN_FAIL',
    
    // Contacts (Admin)
    GET_ALL_CONTACTS_ADMIN_SUCCESS: 'GET_ALL_CONTACTS_ADMIN_SUCCESS',
    GET_ALL_CONTACTS_ADMIN_FAIL: 'GET_ALL_CONTACTS_ADMIN_FAIL',
    GET_CONTACT_DETAIL_ADMIN_SUCCESS: 'GET_CONTACT_DETAIL_ADMIN_SUCCESS',
    GET_CONTACT_DETAIL_ADMIN_FAIL: 'GET_CONTACT_DETAIL_ADMIN_FAIL',
    
    // Statistics
    GET_STATISTICS_KPIS_SUCCESS: 'GET_STATISTICS_KPIS_SUCCESS',
    GET_STATISTICS_REVENUE_TREND_SUCCESS: 'GET_STATISTICS_REVENUE_TREND_SUCCESS',
    GET_STATISTICS_TOP_PRODUCTS_SUCCESS: 'GET_STATISTICS_TOP_PRODUCTS_SUCCESS',
    GET_STATISTICS_BY_CATEGORY_SUCCESS: 'GET_STATISTICS_BY_CATEGORY_SUCCESS',
    GET_STATISTICS_BY_BRAND_SUCCESS: 'GET_STATISTICS_BY_BRAND_SUCCESS',
    GET_STATISTICS_BY_PAYMENT_SUCCESS: 'GET_STATISTICS_BY_PAYMENT_SUCCESS',
    GET_STATISTICS_TOP_CUSTOMERS_SUCCESS: 'GET_STATISTICS_TOP_CUSTOMERS_SUCCESS',
    STATISTICS_FAIL: 'STATISTICS_FAIL',
};

export default actionTypes;
