export {default as Homepage} from "./Homepage"
export {default as Register} from "./auth/Register"
export {default as Login} from "./auth/Login"
export {default as ResetPassword} from "./account/ResetPassword"
export {default as AccountInfo} from "./account/AccountInfo"
export {default as AccountEditModal} from "./account/modals/AccountEditModal"
export {default as OrderHistory} from "./account/OrderHistory"
export {default as ChangePassword} from "./account/ChangePassword"
export {default as AddressBook} from "./account/AddressBook"
export {default as AddressModal} from "./account/modals/AddressModal"
export {default as ProductList} from "./product/ProductList"
export {default as ProductDetail} from "./product/ProductDetail"
export {default as Wishlist} from "./product/Wishlist"
export {default as ProductTabs } from "./product/ProductTabs/index"
export {default as DetailTab } from "./product/ProductTabs/DetailTab"
export {default as UsageTab } from "./product/ProductTabs/UsageTab"
export {default as ShippingTab } from "./product/ProductTabs/ShippingTab"