export const path={
    HOME:'/',
    REGISTER: '/account/register',
    LOGIN:'/account/login',
    ACCOUNT: '/account',
    FORGOT_PASSWORD: '/account/login#recover',
    RESET_PASSWORD: '/account/reset/:userId/:token',
    ORDERS_HISTORY: 'orders',
    CHANGE_PASSWORD: 'changepassword',
    ADDRESSES: 'addresses',
    CALLBACK: '/auth/callback',
    INTRODUCE:'/gioi-thieu-ve-perfumora',
    CONTACT: '/lien-he',
    BRANDS: '/thuong-hieu-a-z',
    COLLECTIONS: '/collections',
    ALL_PRODUCTS: 'all',
    PRODUCTS_FILTERED_BY_CATEGORY: ':slug',
}