export const path={
    HOME:'/',
    REGISTER: '/account/register',
    LOGIN:'/account/login',
    ACCOUNT: '/account',
    FORGOT_PASSWORD: '/account/login#recover',
    RESET_PASSWORD: '/account/reset/:userId/:token',
    ORDERS_HISTORY: 'orders',
    CHANGE_PASSWORD: 'changepassword',
    ADDRESSES: 'addresses',
    CALLBACK: '/auth/callback',
    INTRODUCE:'/gioi-thieu-ve-perfumora',
    BRANDS: '/thuong-hieu-a-z',
    COLLECTIONS: '/collections',
    ALL_PRODUCTS: 'all',
    PRODUCTS_FILTERED_BY_CATEGORY: ':slug',
    PRODUCT_DETAIL: '/products/:slug',
    WISHLIST: '/wishlist',
    SEARCH: '/search',
    MY_VOUCHER: 'vouchers',
    CART: '/cart',
    CHECKOUT: '/checkout',
    MY_ORDER: 'orders',
    CONTACT: '/contact',
    PUCHARSE_GUIDE: '/chinh-sach-thanh-toan-va-huong-dan-mua-hang',
    INSPECTION_GUIDE: '/huong-dan-kiem-hang',
    TERM_OF_USE: '/dieu-khoan-su-dung',
    PURCHASE_POLICY: '/chinh-sach-mua-hang',
    PRIVACY_POLICY: '/chinh-sach-bao-mat-thong-tin',
    RETURN_POLICY: '/chinh-sach-doi-tra-bao-hanh',
    SHIPPING_POLICY: '/chinh-sach-giao-hang',
    PAYMENT_SECURITY_POLICY: '/chinh-sach-bao-mat-thanh-toan'
}