import swaggerJSDoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Perfume Store API',
      version: '1.0.0',
      description: 'API documentation cho hệ thống cửa hàng nước hoa online (Node.js + Express + Sequelize + MySQL)',
    },
    servers: [
      {
        url: 'http://localhost:5000/api',
        description: 'Local server',
      },
      // {
      //   url: 'https://your-production.com/api/v1',
      //   description: 'Production server',
      // },
    ],
    tags: [
      { name: 'Authentication', description: 'Đăng ký, đăng nhập, OAuth (Google/Facebook), refresh token' },
      { name: 'Users', description: 'Quản lý thông tin người dùng và vai trò' },
      { name: 'Roles', description: 'Quản lý vai trò (customer, admin...)' },
      { name: 'Addresses', description: 'Quản lý địa chỉ giao hàng (tỉnh/thành, phường/xã)' },
      { name: 'Brands', description: 'Quản lý thương hiệu nước hoa' },
      { name: 'Categories', description: 'Quản lý danh mục sản phẩm (cây phân cấp)' },
      { name: 'Products', description: 'Quản lý sản phẩm nước hoa' },
      { name: 'Product Images', description: 'Hình ảnh sản phẩm' },
      { name: 'Product Variants', description: 'Biến thể dung tích/giá/kho' },
      { name: 'Carts', description: 'Giỏ hàng và chi tiết giỏ hàng' },
      { name: 'Favorites', description: 'Sản phẩm yêu thích của người dùng' },
      { name: 'Coupons', description: 'Mã giảm giá chung và cá nhân (UserCoupons)' },
      { name: 'Orders', description: 'Quản lý đơn hàng và chi tiết đơn hàng' },
      { name: 'Reviews', description: 'Đánh giá sản phẩm và hình ảnh đánh giá' },
      { name: 'Contacts', description: 'Form liên hệ từ khách hàng' },
    ],
    components: {
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'string', description: 'UUID của người dùng' },
            firstname: { type: 'string', description: 'Tên' },
            lastname: { type: 'string', description: 'Họ' },
            dateOfBirth: { type: 'string', format: 'date', nullable: true },
            gender: { type: 'string', enum: ['male', 'female', 'other'], nullable: true },
            password: { type: 'string', description: 'Mật khẩu đã hash' },
            email: { type: 'string', format: 'email' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'firstname', 'lastname', 'password', 'email'],
        },
        Role: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string', default: 'customer' },
            description: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Address: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            label: { type: 'string', description: 'Nhãn địa chỉ (Nhà, Công ty...)' },
            receiverName: { type: 'string' },
            phone: { type: 'string' },
            addressLine: { type: 'string', nullable: true },
            wardId: { type: 'integer', nullable: true },
            zipCode: { type: 'string', nullable: true },
            isDefault: { type: 'boolean', default: false },
            sortOrder: { type: 'integer', default: 0 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'userId', 'label', 'receiverName', 'phone'],
        },
        Province: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string', nullable: true },
            slug: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Ward: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            provinceId: { type: 'integer' },
            name: { type: 'string', nullable: true },
            slug: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Brand: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            country: { type: 'string' },
            logoUrl: { type: 'string' },
            posterUrl: { type: 'string', nullable: true },
            description: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'name', 'country', 'logoUrl'],
        },
        Category: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            slug: { type: 'string' },
            parentId: { type: 'string', nullable: true },
            sortOrder: { type: 'integer', default: 0 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'name', 'slug'],
        },
        Product: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            brandId: { type: 'string', nullable: true },
            gender: { type: 'string', enum: ['nam', 'nữ', 'unisex'], default: 'unisex' },
            origin: { type: 'string', nullable: true },
            releaseYear: { type: 'integer', nullable: true },
            fragranceGroup: { type: 'string', nullable: true },
            style: { type: 'string', nullable: true },
            scentNotes: { type: 'string', nullable: true },
            description: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'name', 'gender'],
        },
        ProductImage: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            productId: { type: 'string' },
            url: { type: 'string' },
            isThumbnail: { type: 'boolean', default: false },
            sortOrder: { type: 'integer', default: 0 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          required: ['id', 'productId', 'url'],
        },
        ProductVariant: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            productId: { type: 'string' },
            sku: { type: 'string', nullable: true, unique: true },
            volume: { type: 'integer', nullable: true, description: 'Dung tích (ml)' },
            price: { type: 'number', format: 'decimal' },
            originalPrice: { type: 'number', format: 'decimal' },
            discountPercent: { type: 'number', format: 'float', nullable: true },
            stockQuantity: { type: 'integer', default: 0 },
            soldQuantity: { type: 'integer', default: 0 },
            weight: { type: 'number', format: 'decimal', nullable: true },
            isDefault: { type: 'boolean', default: false },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'productId', 'price', 'originalPrice'],
        },
        Cart: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CartItem: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            cartId: { type: 'string' },
            productVariantId: { type: 'string' },
            quantity: { type: 'integer', default: 1 },
            priceAtTime: { type: 'number', format: 'decimal' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Favorite: {
          type: 'object',
          properties: {
            userId: { type: 'string' },
            productId: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Coupon: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            code: { type: 'string', unique: true },
            discountType: { type: 'string', enum: ['percentage', 'fixed'], default: 'percentage' },
            discountValue: { type: 'number', format: 'decimal' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'code', 'discountType', 'discountValue'],
        },
        UserCoupon: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            couponId: { type: 'string' },
            usedAt: { type: 'string', format: 'date-time', nullable: true },
            status: { type: 'string', enum: ['unused', 'used', 'expired'], default: 'unused' },
            validFrom: { type: 'string', format: 'date-time', nullable: true },
            validUntil: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Order: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            addressId: { type: 'string' },
            totalAmount: { type: 'number', format: 'decimal' },
            shippingFee: { type: 'number', format: 'decimal', default: 0 },
            orderStatus: { type: 'string', enum: ['Pending', 'Confirmed', 'Processing', 'Shipped', 'Completed', 'Cancelled'], default: 'Pending' },
            paymentStatus: { type: 'string', enum: ['Pending', 'Confirmed', 'Completed', 'Paid', 'Failed', 'Refunded'], default: 'Pending' },
            paymentMethod: { type: 'string', enum: ['COD', 'ZaloPay'], default: 'COD' },
            paymentGatewayData: { type: 'object', default: {} },
            paymentTransactionId: { type: 'string', nullable: true },
            expiresAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'userId', 'addressId', 'totalAmount', 'orderStatus', 'paymentStatus', 'paymentMethod'],
        },
        OrderItem: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            orderId: { type: 'string' },
            productVariantId: { type: 'string' },
            quantity: { type: 'integer', default: 1 },
            unitPrice: { type: 'number', format: 'decimal' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Review: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            orderItemId: { type: 'string' },
            userId: { type: 'string' },
            title: { type: 'string' },
            content: { type: 'string' },
            rating: { type: 'integer', nullable: true },
            isApproved: { type: 'boolean', default: false },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'orderItemId', 'userId', 'title', 'content'],
        },
        ReviewImage: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            reviewId: { type: 'string' },
            url: { type: 'string' },
            sortOrder: { type: 'integer', default: 0 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Contact: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            email: { type: 'string', format: 'email' },
            message: { type: 'string' },
            status: { type: 'string', enum: ['new', 'replied', 'ignored'], default: 'new' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
          },
          required: ['id', 'name', 'email', 'message'],
        },
        AuthProvider: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            provider: { type: 'string', enum: ['google', 'facebook'] },
            providerUserId: { type: 'string' },
            email: { type: 'string', format: 'email' },
            accessToken: { type: 'string', nullable: true },
            refreshToken: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string' },
            error: { type: 'string', nullable: true },
          },
        },
      },
      securitySchemes: {
  cookieAuth: {
    type: 'apiKey',
    in: 'cookie',
    name: 'access_token',
    description: 'JWT token được lưu trong HttpOnly cookie (tự động gửi kèm)'
  }
},
    },
    security: [{ cookieAuth: [] }],
  },
  apis: ['./src/routes/*.js', './src/controllers/*.js'], // Thêm comment JSDoc trong route để hiển thị endpoint chi tiết
};

const swaggerSpec = swaggerJSDoc(options);

export { swaggerSpec, swaggerUi };